social/projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.project_index, name="project_index"),
    path("<int:pk>/", views.project_detail, name="project_detail"),
]

social/shout/urls.py
# shout/urls

from django.urls import path
from .views import dashboard, profile_list, profile

app_name = "shout"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("profile_list/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile")
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("shout/", include("shout.urls")),
    path('admin/', admin.site.urls),
    path("", include("projects.urls"))
]

social/projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    link = models.CharField(max_length=300, default="")
    image = models.FilePathField(path="/img")

    def __str__(self):
        return f"{self.title} | {self.description}"
    

social/shout/models.py
# shout/models.py

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True 
    )

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.set([instance.profile.id])
        user_profile.save()

class shout(models.Model):
    user = models.ForeignKey(User, related_name='shout', on_delete=models.DO_NOTHING)
    body = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M:%S}): "
            f"{self.body[:30]}..."
        )

# Create a profile for each new user
# post_save.connect(create_profile, sender=User)

social/shout/forms.py
# shout/forms.py
from django import forms
from .models import shout

class ShoutForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
        attrs={
                "placeholder": "Shout something...",
                "class": "textarea is-success is-large",
            }
        ),
        label="",
    )
    class Meta:
        model = shout
        exclude = ("user", )

social/projects/views.py
# projects/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def project_index(request):
    projects = Project.objects.all()
    context = {
        'projects' : projects
    }
    return render(request, 'projects/project_index.html', context)

def project_detail(request, pk):
    project = Project.objects.get(pk=pk)
    context = {
        'project': project
    }

    return render(request, 'projects/project_detail.html', context)

social/shout/views.py
from django.shortcuts import render, redirect
from .models import Profile, shout
from .forms import ShoutForm

# Create your views here.
def dashboard(request):

    form = ShoutForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            shout_a = form.save(commit=False)
            shout_a.user = request.user
            shout_a.save()
            return redirect("shout:dashboard")

    followed_shouts = shout.objects.filter(user__profile__in=request.user.profile.follows.all()).order_by("-created_at")
    return render(request, "shout/dashboard.html", {"form": form, "shout": followed_shouts})

def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "shout/profile_list.html", {"profiles": profiles})

def profile(request, pk):

    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()

    profile = Profile.objects.get(pk=pk)

    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()

    return render(request, "shout/profile.html", {"profile": profile})

social/projects/templates/projects/base.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'project_index' %}">Shinkirou Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'project_index' %}">Home</a>
            </li>
            {% comment %} <li class="nav-item">
              <a class="nav-link" href="{% url 'blog_index' %}">Blog</a>
            </li> {% endcomment %}
          </ul>
        </div>
    </div>

</nav>

<div class="container">
    {% block page_content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

social/projects/templates/projects/project_detail.html
{% extends "projects\base.html" %}
{% load static %}

{% block page_content %}
<h1>{{ project.title }}</h1>
<div class="row">
    <div class="col-md-8">
        <img src="{% static project.image %}" alt="" width="100%">
    </div>
    <div class="col-md-4">
        <h5>About the project:</h5>
        <p>{{ project.description }}</p>
        <br>
        <h5>Technology used:</h5>
        <p>{{ project.technology }}</p>
        <h5>Demo Link </h5>
        <a href={{project.link}}>{{project.title}}</a>
    </div>
</div>
{% endblock %}

social/projects/templates/projects/project_index.html
{% extends "projects\base.html" %}
{% load static %}
{% block page_content %}
<h1>Projects</h1>
<div class="row">
{% for project in projects %}
    <div class="col-md-4">
        <div class="card mb-2">
            <img class="card-img-top" src="{% static project.image %}"> 
            <div class="card-body">
                <h5 class="card-title">{{ project.title }}</h5>
                <p class="card-text">{{ project.description }}</p>
                <a href="{% url 'project_detail' project.pk %}"
                   class="btn btn-primary">
                    Read More
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

social/shout/templates/dashboard.html
<!-- shout/templates/dashboard.html -->

{% extends 'base.html' %}

{% block content %}

<div class="column">
    {% for followed in shout %}
            <div class="box">
                {{ followed.body }}
                <span class="is-small has-text-grey-light">
                    ({{ followed.created_at }} by <font color="#15438c">{{ followed.user.username }} </font>)
                </span>
            </div>
    {% endfor %}
</div>

<div class="column is-one-third">
    <div class="block">
        <a href="{% url 'shout:profile_list' %} ">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <div class="block">
        <a href="{% url 'shout:profile' request.user.profile.id %} ">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>
        <div class="block">
        <h2 class="title is-2">Shout what you feel!</p>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5"
                type="submit">Shout!
        </button>
    </form>
</div>




{% endblock content %}

social/shout/templates/profile.html
<!-- dwitter/templates/dwitter/profile.html -->

{% extends 'base.html' %}

{% block content %}

<div class="column is-full">

    <div class="block">
        <h1 class="title is-1">
           {{profile.user.username|upper}}'s Shouts!
        </h1>

        <form method="post">
            {% csrf_token %}
            <div class="buttons has-addons">
            {% if profile in user.profile.follows.all %}
                <button class="button is-success is-static">Follow</button>
                <button class="button is-danger" name="follow" value="unfollow">
                    Unfollow
                </button>
            {% else %}
                <button class="button is-success" name="follow" value="follow">
                    Follow
                </button>
                <button class="button is-danger is-static">Unfollow</button>
            {% endif %}
            </div>
        </form>
    </div>

    <div class="content">
        {% for sh in profile.user.shout.all %}
            <div class="box">
                {{ sh.body }}
                <span class="is-small has-text-grey-light">
                    ({{ sh.created_at }})
                </span>
            </div>
        {% endfor %}
    </div>
</div>

<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'shout:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'shout:profile' following.id %}">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'shout:profile' follower.id %}">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock content %}

social/shout/templates/profile_list.html
<!-- shout/templates/profile_list.html -->
{% extends 'base.html' %}

{% block content %}

<div class="column">

{% for profile in profiles %}

    <div class="block">
      <div class="card">
        <a href="{% url 'shout:profile' profile.id %}">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  <img src="https://bulma.io/images/placeholders/96x96.png"
                       alt="Placeholder image">
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4">
                  {{ profile.user.username }}
                </p>
                <p class="subtitle is-6">
                  @{{ profile.user.username|lower }}
                </p>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

{% endfor %}

</div>

{% endblock content %}

social/shout/templates/shout/base.html
{% comment %} shout/templates/base.html {% endcomment %}

<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Shout!</title>
</head>

<body>
    <a href="{% url 'shout:dashboard' %} ">
    <section>
        <section class="hero is-msmall is-link mb-4">
            <div class="hero-body">
                <h1 class="title is-1">Shout!</h1>
                <p class="subtitle is-4">
                    Your tiny social network built with Django
                </p>
            </div>   
    </section>

    <div class="container">
        <div class="columns">

        {% block content %}

        {% endblock content %}
        </div>
    </div>

</body>

<footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Shout!</strong> by <a href="https://sethacuestapro.com">Shinkirou</a>. This code is for testing purposes only.
      </p>
    </div>
  </footer>

</html>

social/shout/templates/shout/dashboard.html
<!-- shout/templates/dashboard.html -->

{% extends 'shout\base.html' %}

{% block content %}

<div class="column">
    {% for followed in shout %}
            <div class="box">
                {{ followed.body }}
                <span class="is-small has-text-grey-light">
                    ({{ followed.created_at }} by <font color="#15438c">{{ followed.user.username }} </font>)
                </span>
            </div>
    {% endfor %}
</div>

<div class="column is-one-third">
    <div class="block">
        <a href="{% url 'shout:profile_list' %} ">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <div class="block">
        <a href="{% url 'shout:profile' request.user.profile.id %} ">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>
        <div class="block">
        <h2 class="title is-2">Shout what you feel!</p>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5"
                type="submit">Shout!
        </button>
    </form>
</div>




{% endblock content %}

social/shout/templates/shout/profile.html
<!-- dwitter/templates/dwitter/profile.html -->

{% extends 'shout\base.html' %}

{% block content %}

<div class="column is-full">

    <div class="block">
        <h1 class="title is-1">
           {{profile.user.username|upper}}'s Shouts!
        </h1>

        <form method="post">
            {% csrf_token %}
            <div class="buttons has-addons">
            {% if profile in user.profile.follows.all %}
                <button class="button is-success is-static">Follow</button>
                <button class="button is-danger" name="follow" value="unfollow">
                    Unfollow
                </button>
            {% else %}
                <button class="button is-success" name="follow" value="follow">
                    Follow
                </button>
                <button class="button is-danger is-static">Unfollow</button>
            {% endif %}
            </div>
        </form>
    </div>

    <div class="content">
        {% for sh in profile.user.shout.all %}
            <div class="box">
                {{ sh.body }}
                <span class="is-small has-text-grey-light">
                    ({{ sh.created_at }})
                </span>
            </div>
        {% endfor %}
    </div>
</div>

<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'shout:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'shout:profile' following.id %}">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'shout:profile' follower.id %}">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock content %}

social/shout/templates/shout/profile_list.html
<!-- shout/templates/profile_list.html -->
{% extends 'shout\base.html' %}

{% block content %}

<div class="column">

{% for profile in profiles %}

    <div class="block">
      <div class="card">
        <a href="{% url 'shout:profile' profile.id %}">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  <img src="https://bulma.io/images/placeholders/96x96.png"
                       alt="Placeholder image">
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4">
                  {{ profile.user.username }}
                </p>
                <p class="subtitle is-6">
                  @{{ profile.user.username|lower }}
                </p>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

{% endfor %}

</div>

{% endblock content %}